[build]
  command = "cd client && pnpm install && pnpm build"
  publish = "client/dist"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

